import streamlit as st

st.set_page_config(
    page_title="TCP Connectivity Script Generator",
    page_icon="🔌",
    layout="wide"
)

st.markdown("""
<style>
    .stButton>button { border-radius: 6px; }
    div[data-testid="column"] { padding: 0 4px; }
</style>
""", unsafe_allow_html=True)


# ── Script generators ──────────────────────────────────────────────────────────

def strip_scheme(host: str) -> str:
    """Remove http:// or https:// prefix and any trailing path from a host."""
    import re
    host = re.sub(r'^https?://', '', host)
    host = host.split('/')[0]   # drop any path
    host = host.split(':')[0]   # drop port if embedded in URL
    return host.strip()


def gen_bash(hosts):
    # Use plain "host port timeout" strings — bash doesn't support tuple arrays
    entries = "\n".join(f'    "{strip_scheme(h)} {p} {t}"' for h, p, t in hosts)
    return f"""#!/bin/bash
# TCP Connectivity Tester
# Generated by TCP Script Generator

hosts=(
{entries}
)

GREEN="\\033[0;32m"
RED="\\033[0;31m"
YELLOW="\\033[0;33m"
RESET="\\033[0m"
BOLD="\\033[1m"

pass=0
fail=0

echo ""
echo "${{BOLD}}TCP Connectivity Test — $(date '+%Y-%m-%d %H:%M:%S')${{RESET}}"
echo "$(printf '%.0s─' {{1..52}})"

for entry in "${{hosts[@]}}"; do
    read -r host port timeout <<< "$entry"

    printf "  %-35s:%-6s ${{YELLOW}}◌ testing...${{RESET}}" "$host" "$port"

    start=$(date +%s%3N)

    if (echo > /dev/tcp/$host/$port) &>/dev/null; then
        end=$(date +%s%3N)
        ms=$(( end - start ))
        printf "\\r  %-35s:%-6s ${{GREEN}}✔ OK${{RESET}}  (%s ms)\\n" "$host" "$port" "$ms"
        (( pass++ ))
    else
        printf "\\r  %-35s:%-6s ${{RED}}✘ FAILED${{RESET}}\\n" "$host" "$port"
        (( fail++ ))
    fi

done

echo "$(printf '%.0s─' {{1..52}})"
echo "  ${{GREEN}}✔ $pass reachable${{RESET}}   ${{RED}}✘ $fail unreachable${{RESET}}"
echo ""
"""


def gen_powershell(hosts):
    entries = "\n".join(
        f'    @{{ Host="{strip_scheme(h)}"; Port={p}; Timeout={t} }}' for h, p, t in hosts
    )
    return f"""# TCP Connectivity Tester
# Generated by TCP Script Generator

$hosts = @(
{entries}
)

$pass = 0
$fail = 0

Write-Host ""
Write-Host ("TCP Connectivity Test — " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss")) -ForegroundColor White
Write-Host ("─" * 52)

foreach ($entry in $hosts) {{
    $label = "$($entry.Host):$($entry.Port)"
    Write-Host ("  {{0,-42}}" -f $label) -NoNewline
    Write-Host "◌ testing..." -ForegroundColor Yellow -NoNewline

    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $result = Test-NetConnection -ComputerName $entry.Host -Port $entry.Port -WarningAction SilentlyContinue -InformationLevel Quiet
    $sw.Stop()
    $ms = $sw.ElapsedMilliseconds

    Write-Host "`r" -NoNewline
    Write-Host ("  {{0,-42}}" -f $label) -NoNewline

    if ($result) {{
        Write-Host "✔ OK  ($ms ms)" -ForegroundColor Green
        $pass++
    }} else {{
        Write-Host "✘ FAILED" -ForegroundColor Red
        $fail++
    }}
}}

Write-Host ("─" * 52)
Write-Host "  ✔ $pass reachable   ✘ $fail unreachable"
Write-Host ""
"""


def gen_python(hosts):
    entries = "\n".join(
        f'    ("{strip_scheme(h)}", {p}, {t}),' for h, p, t in hosts
    )
    return f"""#!/usr/bin/env python3
# TCP Connectivity Tester
# Generated by TCP Script Generator

import socket
import time
from datetime import datetime

hosts = [
{entries}
]

GREEN  = "\\033[0;32m"
RED    = "\\033[0;31m"
YELLOW = "\\033[0;33m"
RESET  = "\\033[0m"
BOLD   = "\\033[1m"

pass_count = 0
fail_count = 0

print()
print(f"{{BOLD}}TCP Connectivity Test — {{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}}{{RESET}}")
print("─" * 52)

for host, port, timeout in hosts:
    label = f"{{host}}:{{port}}"
    print(f"  {{label:<42}}{{YELLOW}}◌ testing...{{RESET}}", end="\\r", flush=True)

    start = time.time()
    try:
        with socket.create_connection((host, port), timeout=timeout):
            ms = round((time.time() - start) * 1000, 1)
            print(f"  {{label:<42}}{{GREEN}}✔ OK{{RESET}}  ({{ms}} ms)          ")
            pass_count += 1
    except socket.timeout:
        print(f"  {{label:<42}}{{RED}}✘ TIMEOUT{{RESET}}              ")
        fail_count += 1
    except ConnectionRefusedError:
        print(f"  {{label:<42}}{{RED}}✘ REFUSED{{RESET}}              ")
        fail_count += 1
    except socket.gaierror:
        print(f"  {{label:<42}}{{RED}}✘ DNS FAIL{{RESET}}             ")
        fail_count += 1
    except OSError as e:
        print(f"  {{label:<42}}{{RED}}✘ ERROR: {{e}}{{RESET}}")
        fail_count += 1

print("─" * 52)
print(f"  {{GREEN}}✔ {{pass_count}} reachable{{RESET}}   {{RED}}✘ {{fail_count}} unreachable{{RESET}}")
print()
"""


# ── Session state ──────────────────────────────────────────────────────────────
if "rows" not in st.session_state:
    st.session_state.rows = [
        {"host": "", "port": 1521, "timeout": 5},
        {"host": "", "port": 22,   "timeout": 5},
    ]


# ── UI ─────────────────────────────────────────────────────────────────────────
st.title("🔌 TCP Connectivity Script Generator")
st.caption("Enter your hosts and ports, choose a script type, and download a ready-to-run script.")

st.divider()

# Input table header
c1, c2, c3, c4 = st.columns([5, 2, 2, 1])
c1.markdown("**Host / IP**")
c2.markdown("**Port**")
c3.markdown("**Timeout (s)**")

rows_to_keep = []
for i, row in enumerate(st.session_state.rows):
    c1, c2, c3, c4 = st.columns([5, 2, 2, 1])
    h = c1.text_input("host", value=row["host"], placeholder="hostname or IP address",
                      label_visibility="collapsed", key=f"h_{i}")
    p = c2.number_input("port", value=row["port"], min_value=1, max_value=65535,
                        label_visibility="collapsed", key=f"p_{i}")
    t = c3.number_input("timeout", value=row["timeout"], min_value=1, max_value=60,
                        label_visibility="collapsed", key=f"t_{i}")
    remove = c4.button("✕", key=f"rm_{i}")
    if not remove:
        rows_to_keep.append({"host": h, "port": int(p), "timeout": int(t)})

st.session_state.rows = rows_to_keep

if st.button("＋  Add host"):
    st.session_state.rows.append({"host": "", "port": 22, "timeout": 5})
    st.rerun()

st.divider()

# Script type + download
targets = [(r["host"].strip(), r["port"], r["timeout"])
           for r in st.session_state.rows if r["host"].strip()]

col_sel, col_dl = st.columns([2, 3])

with col_sel:
    script_type = st.selectbox(
        "Script type",
        ["Bash (.sh)", "PowerShell (.ps1)", "Python (.py)"],
        label_visibility="visible"
    )

if targets:
    if script_type == "Bash (.sh)":
        code = gen_bash(targets)
        filename = "connectivity_test.sh"
        mime = "text/x-sh"
    elif script_type == "PowerShell (.ps1)":
        code = gen_powershell(targets)
        filename = "connectivity_test.ps1"
        mime = "text/plain"
    else:
        code = gen_python(targets)
        filename = "connectivity_test.py"
        mime = "text/x-python"

    with col_dl:
        st.write("")
        st.download_button(
            label=f"⬇  Download {filename}",
            data=code,
            file_name=filename,
            mime=mime,
            use_container_width=False,
        )

    st.divider()
    st.markdown(f"**Preview — `{filename}`**")
    st.code(code, language="bash" if "Bash" in script_type else
            ("powershell" if "PowerShell" in script_type else "python"))

else:
    st.info("Add at least one host to generate a script.")
